### PR TITLE
Update for latest wordpress

### PR DESCRIPTION
**Pull request by Wiljami**
Clean up the code to match phpcs and fix few typos.

This is a very simple plugin and since it's one that we have used few times, so it would be nice to get it updated for the latest wordpress. Especially since now we have the git actions working.

### CODE REVIEW

**Review by sjaks — APPROVED** [review]
Tested and works:

Screenshot from 2020-07-30 08-45-41
Screenshot from 2020-07-30 08-45-57

**Comment by ottok** [comment]
Maybe bump WP compatibility directly to 5.5?

We got this heads-up email from WP.org:

> WordPress 5.5 is scheduled to be released on August 11th. Are your plugins ready?
> 
> After testing your plugins and ensuring compatibility, it only takes a few moments to change the readme "Tested up to:" value to 5.5. This information provides peace of mind to users and encourages them to update to the latest version.
> 
> Here are the current "Tested up to:" values for each of your plugins:
> 
>  * https://wordpress.org/plugins/custom-bulk-actions/ (tested up to 4.9.15)
>  * https://wordpress.org/plugins/dashboard-log-monitor/ (tested up to 4.9.15)
>  * https://wordpress.org/plugins/https-domain-alias/ (tested up to 4.9.15)
>  * https://wordpress.org/plugins/simple-header-footer-html/ (tested up to 4.9.15)
>  * https://wordpress.org/plugins/subscribe-google-groups/ (tested up to 4.9.15)
>  * https://wordpress.org/plugins/woo-pakettikauppa/ (tested up to 5.4.2)
>  * https://wordpress.org/plugins/woocommerce-mws-sync/ (tested up to 4.9.15)
>  * https://wordpress.org/plugins/wp-nettix-sync/ (tested up to 4.9.15)
>  * https://wordpress.org/plugins/wp-spam-question-filter/ (tested up to 4.8.14)
> 
> For each plugin that is compatible, you don't need to release a new version — just change the stable version's readme value.
> 
> Looking to get more familiar with 5.5? Read this roundup post on the core development blog to learn more about the varous changes coming to core with this major release:
> 
> https://make.wordpress.org/core/2020/07/30/wordpress-5-5-field-guide/
> 
> There are six areas that specific focus should be given as plugin-related changes coming in 5.5:
> 
> 1.) Note the version of jQuery shipped in core will be updated in 5.6 and as a first step jquery-migrate is no longer enqueued by default in 5.5. Updates to your code are required if you rely on jquery-migrate or .live() to function properly as they are being removed. You can verify this by checking your code with WP_DEBUG enabled to make sure you are not using deprecated code. Please do this to avoid unnecessary support requests and negative reviews for your plugin:
> https://make.wordpress.org/core/2020/06/29/updating-jquery-version-shipped-with-wordpress/
> 
> 2.) Note the new plugin auto-update UI and how to ensure your plugin is ready for the new auto-updates system:
> https://make.wordpress.org/core/2020/07/15/controlling-plugin-and-theme-auto-updates-ui-in-wordpress-5-5/
> 
> 3.) Note the Block Directory guidelines (https://make.wordpress.org/plugins/2020/07/22/proposed-block-directory-guidelines/) and how to get your block plugin added to the Block Directory:
> https://make.wordpress.org/plugins/2020/07/11/you-can-now-add-your-own-plugins-to-the-block-directory/
> 
> 4.) Note the new XML sitemap feature and how it can be integrated with your plugin:
> https://make.wordpress.org/core/2020/07/22/new-xml-sitemaps-functionality-in-wordpress-5-5/
> 
> 5.) Note the deprecated $HTTP_RAW_POST_DATA global variable in the PHP related improvements & changes devnote:
> https://make.wordpress.org/core/2020/07/14/php-related-improvements-changes-wordpress-5-5-edition/
> 
> 6.) Note the various plugin recommendations in the miscellaneous changes devnote:
> https://make.wordpress.org/core/2020/07/29/miscellaneous-developer-focused-changes-in-wordpress-5-5/
> 
> In order to ensure compatibility, you can download and beta test your plugin with the latest WordPress version here: https://make.wordpress.org/core/handbook/testing/beta-testing/
> 
> Thank you for all you do for the WordPress community, and we hope you enjoy 5.5 as much as we do.
> 
> 
> WordPress core contributors

**Comment by Wiljami** [comment]
I tested this out in 5.5 WordPress beta and it still worked as intended.

**Review by elguitar — APPROVED** [review]
Looks nice! Go ahead and merge

**Pull request merged**
